---

# Config
ansible_become_user: root
ansible_become_pass: "{{ vaulted.host_vars.webserver_local.ansible_become_pass }}"

# MySQL
mysql_root_username: root
mysql_root_password: "{{ vaulted.host_vars.webserver_local.mysql_root_password }}"

# Backup folder list
remote_backup_folders_list:
  - /home/ezra
  - /etc/nginx
  - /etc/php5/fpm
  - /etc/supervisor
  - /etc/ssh
  - /lib/ufw
  - /var/spool/cron/crontabs
  - /var/www
  - /var/log