- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=root/.my.j2 dest=/root/.my.cnf owner=root mode=0600

# - name: update .my.cnf file with new root password
#   lineinfile: 'dest=/root/.my.cnf regexp="^password=.*" line="password={{ mysql_root_password }}" state=present'

# Need to do this for idempotency, see
# http://docs.ansible.com/mysql_user_module.html
# - name: update mysql root password for all root accounts
#   mysql_user: 
#     name: root
#     host: localhost
#     password: "{{ mysql_root_password }}"

- name: ensure anonymous users are not in the database
  mysql_user: 
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Create MySQL Backup User
  mysql_user: 
    name: "{{ mysql_backup_user_username }}"
    password: "{{ mysql_backup_user_password }}"
    priv: "*.*:LOCK TABLES, SELECT, FILE, RELOAD, SUPER, SHOW VIEW"
    state: present